MESSAGE(STATUS "\nFindSCLang init...")
MESSAGE(STATUS "SC_SRC_DIR : " ${SC_SRC_DIR})
MESSAGE(STATUS "SC_BUILD_DIR : " ${SC_BUILD_DIR})

FIND_PATH(
  SC_LANG_INCLUDE_DIR
  NAMES SC_LanguageClient.h
  PATHS "${SC_SRC_DIR}/include/lang"
  )

FIND_PATH(
  SC_LANG_INCLUDE_DIRS
  NAMES SC_Export.h
  PATHS "${SC_SRC_DIR}/include/common"
  )

FIND_PATH(
  SC_LANG_LIBRARY_DIR
  NAMES libsclang.lib
  PATHS "${SC_BUILD_DIR}/lang"
  PATH_SUFFIXES Release
)

FIND_LIBRARY(
  SC_LANG_LIBRARY
  NAMES libsclang sclang 
  #HINTS ${SC_BUILD_DIR}/lang
  PATHS ${SC_LANG_LIBRARY_DIR}
  PATH_SUFFIXES Release
)

SET(SC_LANG_FOUND FALSE)

IF( SC_LANG_INCLUDE_DIR AND SC_LANG_LIBRARY)
  SET(SC_LANG_FOUND TRUE)
  MESSAGE(STATUS "\tSC_LANG_INCLUDE_DIR : " ${SC_LANG_INCLUDE_DIR})
  MESSAGE(STATUS "\tSC_LANG_INCLUDE_DIRS : " ${SC_LANG_INCLUDE_DIRS})
  MESSAGE(STATUS "\tSC_LANG_LIBRARY : " ${SC_LANG_LIBRARY})
  MESSAGE(STATUS "\tSC_LANG_LIBRARY_DIR : " ${SC_LANG_LIBRARY_DIR})
ENDIF()

MESSAGE(STATUS "FindSCLang done...\n")
