MESSAGE(STATUS "\nFindSC init...")
MESSAGE(STATUS "SC_SRC_DIR : " ${SC_SRC_DIR})

FIND_PATH(
    LANG_INCLUDE_DIR
    NAMES SC_LanguageClient.hpp SC_LanguageClient.h
    PATHS ${SC_SRC_DIR}/include/lang/
)
MESSAGE(STATUS "LANG_INCLUDE_DIR : " ${LANG_INCLUDE_DIR})

FIND_LIBRARY(
    LANG_LINK_DIR
    NAMES sclang
    HINTS ${SC_BUILD_DIR}/lang/Release/ ${SC_BUILD_DIR}/lang
    PATHS ${SC_BUILD_DIR}/lang/Release/ ${SC_BUILD_DIR}/lang
)

MESSAGE(STATUS "LANG_LINK_DIR : " ${LANG_LINK_DIR})

MESSAGE(STATUS "FindSC done...")
