MESSAGE(STATUS "\nFindSCLang init...")
MESSAGE(STATUS "CMAKE_SOURCE_DIR : " ${CMAKE_SOURCE_DIR})
MESSAGE(STATUS "CMAKE_BINARY_DIR : " ${CMAKE_BINARY_DIR})

FIND_PATH(
  SCBRIDGE_INCLUDE_DIR
  NAMES ScBridge.h
  PATHS "${CMAKE_SOURCE_DIR}/ScBridge"
  )

FIND_PATH(
  SCBRIDGE_LIBRARY_DIR
  NAMES libScBridge.a ScBridge.lib
  PATHS "${CMAKE_BINARY_DIR}/ScBridge"
  PATH_SUFFIXES Release Debug
)

FIND_LIBRARY(
  SCBRIDGE_LIBRARY
  NAMES libScBridge ScBridge
  PATHS "${CMAKE_BINARY_DIR}/ScBridge/"
  PATH_SUFFIXES Release
)

SET(SCBRIDGE_FOUND FALSE)

IF( SCBRIDGE_INCLUDE_DIR AND SCBRIDGE_LIBRARY)
  SET(SCBRIDGE_FOUND TRUE)
  MESSAGE(STATUS "\tSCBRIDGE_INCLUDE_DIR : " ${SCBRIDGE_INCLUDE_DIR})
  MESSAGE(STATUS "\tSCBRIDGE_LIBRARY_DIR : " ${SCBRIDGE_LIBRARY_DIR})
  MESSAGE(STATUS "\tSCBRIDGE_LIBRARY : " ${SCBRIDGE_LIBRARY})
ENDIF()

MESSAGE(STATUS "FindSCLang done...\n")
